package com.mycompany.spms2;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author welcome
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    
    private static final String USERNAME = "root";
    private static final String PWD = "mmm";
    private static final String CONSTR = "jdbc:mysql://localhost:3306/spms";
    Connection dbcon = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    int columnCount;
    int i;
    int selectedID;
    int deleteAction;
    private Object JoptionPane;
    
    
    public Attendance() throws SQLException {
        initComponents();
        listAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtEMPID = new javax.swing.JTextField();
        txtMONTH = new javax.swing.JTextField();
        txtWORKHOURS = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttendance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("                      ATTENDANCE SCREEN");

        btnMainMenu.setText("MAINMENU");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(btnMainMenu)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMainMenu)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 740, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("EMPID");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DATE");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("WORKHOURS");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MONTH");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtID.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtWORKHOURS, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMONTH, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEMPID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEMPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtMONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtWORKHOURS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 500, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnModify.setText("MODIFY");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnADD)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDelete)
                        .addComponent(btnModify)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnADD)
                .addGap(31, 31, 31)
                .addComponent(btnModify)
                .addGap(27, 27, 27)
                .addComponent(btnDelete)
                .addGap(28, 28, 28)
                .addComponent(btnExit)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 210, 240));

        jTableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Emp ID", "Month", "Date", "Work Hours"
            }
        ));
        jTableAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAttendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAttendance);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 60, 740, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void listAttendance() throws SQLException{
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           dbcon = DriverManager.getConnection(CONSTR,USERNAME,PWD);
           String sqlQuery = "select ID,EMPID,MONTH,DATE,WORKHOURS from spms.attendance order by ID";
           ps = dbcon.prepareStatement(sqlQuery);
           rs = ps.executeQuery();
           System.out.println("DB connected for lisitng attendance");
           ResultSetMetaData stData = rs.getMetaData();
           columnCount = stData.getColumnCount();
           DefaultTableModel tableAttendance = (DefaultTableModel) jTableAttendance.getModel();
           tableAttendance.setRowCount(0);
           
            while (rs.next()) {
                Vector columnData = new Vector();
               
                for (i = 1; i <= columnCount; i++) {
                    columnData.add(rs.getInt("ID"));
                    columnData.add(rs.getInt("EMPID"));
                    columnData.add(rs.getString("MONTH"));
                    columnData.add(rs.getString("DATE"));
                    columnData.add(rs.getString("WORKHOURS"));
                    
                }
                tableAttendance.addRow(columnData);

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    
    
    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        Menuscreen m = new Menuscreen();
        m.setVisible(true);
        
        dispose(); 
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");               
        dbcon = DriverManager.getConnection(CONSTR,USERNAME,PWD);
        String sqlQuery = "insert into spms.attendance (EMPID,MONTH,DATE,WORKHOURS)value (?,?,?,?)";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateDATE = sdf.format(txtDate.getDate());
        
            
        ps = dbcon.prepareStatement(sqlQuery);
        System.out.println("DB connected for adding attendance");
        ps.setString(1,txtEMPID.getText());
        ps.setString(2,txtMONTH.getText());
        ps.setString(3,dateDATE);
        ps.setString(4,txtWORKHOURS.getText());
        
        System.out.println(sqlQuery);
        ps.executeUpdate();
        System.out.println("Insert Completed");
        
        JOptionPane.showMessageDialog(this,"Attendance added successfully");
        // Clear all the Textfields after insert
        txtEMPID.setText("");
        txtMONTH.setText("");
        txtWORKHOURS.setText("");
        listAttendance();
        
}
        catch(HeadlessException | ClassNotFoundException | SQLException ex)
                {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(null,ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tableAttendance = (DefaultTableModel) jTableAttendance.getModel();
        int selectedRows = jTableAttendance.getSelectedRow();
        
        try{
            selectedID =  Integer.parseInt(tableAttendance.getValueAt(selectedRows,0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            dbcon = DriverManager.getConnection(CONSTR,USERNAME,PWD);
            
            String sqlQuery = " update attendance set EMPID=?,MONTH=?,DATE=?,WORKHOURS=? where ID = ? ";

            ps = dbcon.prepareStatement(sqlQuery);
            System.out.println("DB connected for modification");
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateDATE = sdf.format(txtDate.getDate());
            
            
        ps.setString(1,txtEMPID.getText());
        ps.setString(2,txtMONTH.getText());
        ps.setString(3,dateDATE);
        ps.setString(4,txtWORKHOURS.getText());
        ps.setInt(5,selectedID);
            
        ps.executeUpdate();
        System.out.println("Modify Completed");
        JOptionPane.showMessageDialog(this,"Attendance modified successfully");
        listAttendance();
        
         // Clear all the Textfields after insert
        txtID.setText("");
        txtEMPID.setText("");
        txtMONTH.setText("");
        txtWORKHOURS.setText("");
        txtDate.requestFocus();
       
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
            ex.printStackTrace();
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnModifyActionPerformed

    private void jTableAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAttendanceMouseClicked
        try {
            // TODO add your handling code here:
            DefaultTableModel tableAttendance = ( DefaultTableModel) jTableAttendance.getModel();
            int selectedRows = jTableAttendance.getSelectedRow();
            
            txtID.setText(tableAttendance.getValueAt(selectedRows,0).toString());
            txtEMPID.setText(tableAttendance.getValueAt(selectedRows,1).toString());
            txtMONTH.setText(tableAttendance.getValueAt(selectedRows,2).toString());
            
            // convert select query date as string (DOB)
            String strDate = (tableAttendance.getValueAt(selectedRows, 3).toString());
            // To convert the sql date  string format into java date format
            Date dateDOBConvert;
            dateDOBConvert = new SimpleDateFormat("yyyy-MM-dd").parse(strDate);
            txtDate.setDate(dateDOBConvert);
            txtWORKHOURS.setText(tableAttendance.getValueAt(selectedRows,4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTableAttendanceMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
    DefaultTableModel  tableAttendance   = (DefaultTableModel)  jTableAttendance.getModel();
    int selectedRows = jTableAttendance.getSelectedRow();
         try{
        selectedID = Integer.parseInt(tableAttendance.getValueAt(selectedRows,0).toString());
        
        deleteAction  = JOptionPane.showConfirmDialog(null,"Do you to delete this record","Warning",JOptionPane.YES_NO_OPTION);
        if(deleteAction == JOptionPane.YES_OPTION)
         {
            Class.forName("com.mysql.cj.jdbc.Driver");
            dbcon = DriverManager.getConnection(CONSTR,USERNAME,PWD);
            
            String sqlQuery = "delete from attendance where ID = ?";
            ps = dbcon.prepareStatement(sqlQuery);
            
            System.out.println("DB Connected for deleting the attendance");
            ps.setInt(1,selectedID);
            ps.executeUpdate();
             System.out.println("Delete COmpleted");
        
        JOptionPane.showMessageDialog(this,"Attendance deleted successfully");
        
        // Clear all the Textfields after insert
        txtID.setText("");
        txtEMPID.setText("");
        txtMONTH.setText("");
        txtWORKHOURS.setText("");
        txtDate.requestFocus();
       
        listAttendance();
        
    }
    }
    catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
                ex.printStackTrace();
            }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Attendance().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAttendance;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEMPID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMONTH;
    private javax.swing.JTextField txtWORKHOURS;
    // End of variables declaration//GEN-END:variables
}
