package com.mycompany.spms2;

import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author welcome
 */
public class Menuscreen extends javax.swing.JFrame {

    /**
     * Creates new form Menuscreen
     */
    public Menuscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        JLoginMenu = new javax.swing.JMenuItem();
        JMainMenu = new javax.swing.JMenuItem();
        JEmpMenu = new javax.swing.JMenuItem();
        JAttendanceMenu = new javax.swing.JMenuItem();
        JSalaryMenu = new javax.swing.JMenuItem();
        JExitMenu = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");

        jMenu7.setText("jMenu7");

        jMenu11.setText("jMenu11");

        jMenu12.setText("File");
        jMenuBar2.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar2.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar3.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar3.add(jMenu15);

        jMenu16.setText("File");
        jMenuBar4.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar4.add(jMenu17);

        jMenu18.setText("File");
        jMenuBar5.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar5.add(jMenu19);

        jMenu20.setText("File");
        jMenuBar6.add(jMenu20);

        jMenu21.setText("Edit");
        jMenuBar6.add(jMenu21);

        jMenu22.setText("File");
        jMenuBar7.add(jMenu22);

        jMenu23.setText("Edit");
        jMenuBar7.add(jMenu23);

        jMenu24.setText("File");
        jMenuBar8.add(jMenu24);

        jMenu25.setText("Edit");
        jMenuBar8.add(jMenu25);

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 430));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("                        SOFTWARE PERSONEL MANAGEMENT SYSTEM ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 650, 40));

        jMenu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu8.setText("MAIN MENU");
        jMenu8.setName(""); // NOI18N

        JLoginMenu.setText("Login");
        JLoginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLoginMenuActionPerformed(evt);
            }
        });
        jMenu8.add(JLoginMenu);

        JMainMenu.setText("Menu");
        jMenu8.add(JMainMenu);

        JEmpMenu.setText("Employee Registration");
        JEmpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmpMenuActionPerformed(evt);
            }
        });
        jMenu8.add(JEmpMenu);

        JAttendanceMenu.setText("Attendance ");
        JAttendanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAttendanceMenuActionPerformed(evt);
            }
        });
        jMenu8.add(JAttendanceMenu);

        JSalaryMenu.setText("GenerateSalary");
        JSalaryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalaryMenuActionPerformed(evt);
            }
        });
        jMenu8.add(JSalaryMenu);

        JExitMenu.setText("Exit");
        JExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JExitMenuActionPerformed(evt);
            }
        });
        jMenu8.add(JExitMenu);

        jMenuBar1.add(jMenu8);
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLoginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLoginMenuActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_JLoginMenuActionPerformed

    private void JExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JExitMenuActionPerformed
        // TODO add your handling code here:
          dispose();
    }//GEN-LAST:event_JExitMenuActionPerformed

    private void JSalaryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalaryMenuActionPerformed
        // TODO add your handling code here:
        GenerateSalary s = null;
        try {
            s = new GenerateSalary();
        } catch (SQLException ex) {
            Logger.getLogger(Menuscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_JSalaryMenuActionPerformed

    private void JAttendanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAttendanceMenuActionPerformed
        // TODO add your handling code here:
        Attendance a = null;
        try {
            a = new Attendance();
        } catch (SQLException ex) {
            Logger.getLogger(Menuscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_JAttendanceMenuActionPerformed

    private void JEmpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmpMenuActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeRegistration e = new EmployeeRegistration();
            e.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menuscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JEmpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JAttendanceMenu;
    private javax.swing.JMenuItem JEmpMenu;
    private javax.swing.JMenuItem JExitMenu;
    private javax.swing.JMenuItem JLoginMenu;
    private javax.swing.JMenuItem JMainMenu;
    private javax.swing.JMenuItem JSalaryMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
